// Isolated visual fixture. Product routes never import this module.
import {
  TRINITY_SOURCE_CATEGORY_META,
  TRINITY_STAGE_META,
} from './trinity-model';
import type { TrinitySituationData } from './trinity-types';

export const TRINITY_SAMPLE_FIXTURE: TrinitySituationData = {
  meta: {
    name: 'WiseLink 信息聚合与协同评估 · 构造示例',
    asOf: '2026-09-16',
    origin: 'ISOLATED_EXAMPLE',
    currentHostVerified: false,
  },
  stages: TRINITY_STAGE_META,
  sourceCategories: TRINITY_SOURCE_CATEGORY_META,
  availability: 'complete',
  coverage: {
    matterTotal: 'complete', matters: 'complete', assessment: 'complete',
    sources: 'complete', events: 'complete', knowledge: 'complete',
  },
  matters: [
    {
      id: 'm1', code: '事项 01', title: '显示系统软件改进与验证条件',
      fleet: '777', ata: '31', tag: '综合待更新',
      status: '最新问题工作已保存，原综合尚未覆盖',
      brief: '补充验证资料预计日期已改为待定；SB自身有效版要求仍需独立核对。',
      next: '核对准确软件子集和验证资料可用性。', attention: true,
      synthesisPending: true,
      activeAssessmentStages: [
        'question', 'conditions', 'analysis', 'synthesis', 'review', 'update',
      ],
    },
    {
      id: 'm2', code: '事项 02', title: '飞行管理数据校验异常',
      fleet: '737NG', ata: '34', tag: '关键条件待核',
      status: '已保存局部认识',
      brief: '措施说明只明确针对其中一种现象，需要核对本次发生条件。',
      next: '核对本次异常对应的现象分支。', attention: true,
      synthesisPending: false,
      activeAssessmentStages: ['question', 'conditions', 'analysis', 'synthesis'],
    },
    {
      id: 'm3', code: '事项 03', title: '液压泵检查与适用范围',
      fleet: '787', ata: '29', tag: '范围待核',
      status: '当前认识有条件成立',
      brief: '静态检查未见异常，仅说明所覆盖检查状态。',
      next: '补充目标序号范围并保留检查能力边界。', attention: true,
      synthesisPending: false,
      activeAssessmentStages: ['question', 'conditions', 'analysis', 'synthesis'],
    },
    {
      id: 'm4', code: '事项 04', title: '间歇告警调查资料归并',
      fleet: '777', ata: '31', tag: '继续调查',
      status: '尚未形成综合',
      brief: '多份报道可能转述同一事件，当前没有确认共同根因。',
      next: '核对原事件身份及各次发生条件。', attention: true,
      synthesisPending: true,
      activeAssessmentStages: ['question', 'conditions', 'analysis'],
    },
    {
      id: 'm5', code: '事项 05', title: '显示条件原文更正',
      fleet: '737NG', ata: '31', tag: '原文更正',
      status: '新工作已保存',
      brief: '否定条件已按原件更正，旧综合仍可回看。',
      next: '核对旧综合中受影响的准确范围。', attention: true,
      synthesisPending: true,
      activeAssessmentStages: ['conditions', 'analysis', 'update'],
    },
    {
      id: 'm6', code: '事项 06', title: '软件组合兼容性说明',
      fleet: '777', ata: '22', tag: '持续关注',
      status: '当前综合覆盖已有工作',
      brief: '兼容性说明只覆盖组合表列明的各项版本。',
      next: '新组合或新事件出现时复看。', attention: false,
      synthesisPending: false,
      activeAssessmentStages: ['question', 'conditions', 'analysis', 'synthesis'],
    },
  ],
  sources: [
    { id: 's1', matter: 'm1', category: 'documents', title: 'SB-A',
      version: 'R02', contribution: '保留措施自身条件与准确版本。' },
    { id: 's2', matter: 'm1', category: 'documents', title: 'FTD-B',
      version: 'R03', contribution: '说明补充验证资料的最新预期。' },
    { id: 's3', matter: 'm1', category: 'configuration', title: '目标对象记录',
      version: '本次快照', contribution: '标准A已知，A1子集仍待核。' },
    { id: 's4', matter: 'm1', category: 'operation', title: '显示异常记录',
      version: '本次记录', contribution: '补充现象背景，完整工况尚未取得。' },
    { id: 's5', matter: 'm1', category: 'history', title: '原有问题分析',
      version: '工作修订 3', contribution: '保留旧综合及其原始范围。' },
    { id: 's6', matter: 'm1', category: 'knowledge', title: '条件核对方法',
      version: '方法版本 2', contribution: '帮助区分文件规定与对象事实。' },
    { id: 's7', matter: 'm1', category: 'engineer', title: '工程师补充',
      version: '本轮输入', contribution: '提出更换组件是否满足条件的问题。' },
    { id: 's8', matter: 'm2', category: 'documents', title: '说明 C',
      version: 'R01', contribution: '区分两个现象分支和措施范围。' },
    { id: 's9', matter: 'm3', category: 'documents', title: 'SB-D',
      version: 'R02', contribution: '限定泵件适用范围。' },
  ],
  events: [
    { id: 'e1', matter: 'm1', date: '2026-09-14',
      title: '问题工作已更新，综合待接续', kind: 'assessment' },
  ],
  knowledge: [
    { id: 'k1', matter: 'm1', phase: 'analysis',
      title: '资料发布预期与实施要求如何分别理解',
      version: '工作修订 4', status: '待更新综合', reuse: ['m1'] },
  ],
  reviewConditions: [],
};
