export const S1000D_DOCUMENT_SOURCE = Symbol('S1000D_DOCUMENT_SOURCE');
export const S1000D_SOURCE_USE_AUTHORIZER = Symbol(
  'S1000D_SOURCE_USE_AUTHORIZER',
);
export const S1000D_STRUCTURED_PACKAGE_PRODUCER = Symbol(
  'S1000D_STRUCTURED_PACKAGE_PRODUCER',
);
