/** Saved candidate reading content. Its reading depths are never generated by GET. */
export interface AssessmentReadingContent {
  schemaVersion: 'wiselink.3_1.assessment_reading.v1';
  headline: string;
  listBrief: string;
  lead: string;
  claims: AssessmentReadingClaim[];
  /** Claims whose conditions, negations or conflicts must remain visible. */
  decisiveClaimIds: string[];
}

export interface AssessmentReadingClaim {
  claimId: string;
  text: string;
  basis: 'SOURCE_FACT' | 'CONDITIONAL_INFERENCE';
  premises: AssessmentClaimPremise[];
}

export interface AssessmentClaimPremise {
  evidenceRef: string;
  role: 'SUPPORTS' | 'LIMITS' | 'CONTEXT' | 'CONFLICTS';
  explanation: string;
  limitation: string | null;
}

export interface DialogueEvidenceSource {
  requestRef: string;
  contributionRef: string;
  revision: number;
  contextWorkItemIds: string[];
}

/** Host-issued premises keep their original carrier identity and version. */
export type AssessmentEvidence = {
  evidenceRef: string;
  title: string;
  versionLabel: string | null;
  excerpt: string;
  dialogueSource?: DialogueEvidenceSource;
} & (
  | {
      kind: 'DOCUMENT_PASSAGE';
      workItemId: string;
      documentVersionId: string;
      sourceRefId: string;
      locator: string;
    }
  | {
      kind: 'ENGINEER_STATEMENT';
      origin: 'REVIEW_CONVERSATION';
      reviewConversationId: string;
      reviewTurnId: string;
      engineerSuppliedInputId: string;
      recordedAt: string;
    }
  | {
      kind: 'ENGINEER_STATEMENT';
      origin: 'ENGINEER_REVIEW_LEDGER';
      workItemId: string;
      reviewRevision: number;
      sequence: number;
      sourceRefId: string;
      locator: string;
      recordedAt: string;
    }
  | {
      kind: 'HOST_FACT';
      workItemId: string;
      workItemRevision: number;
      factRef: string;
      recordedAt: string;
    }
  | {
      kind: 'QUERY_RECEIPT';
      receiptRef: string;
      checkedScope: string;
      queriedAt: string;
      coverage: 'COMPLETE' | 'PARTIAL';
      /** A retrieval response is supplemental material, not verified source text. */
      queryProvenance?: {
        origin: 'AILY_RETRIEVAL';
        queryText: string;
        status: 'COMPLETED' | 'FAILED' | 'UNKNOWN';
        originalDocumentsVerified: false;
      };
    }
  | {
      kind: 'PRIOR_RESULT';
      resultRef: string;
      resultRevision: number;
      /** A previous candidate is context, not a new independent source fact. */
      originalEvidenceRefs: string[];
    }
  | {
      kind: 'ENGINEER_ATTACHMENT';
      workItemId: string;
      reviewConversationId: string;
      reviewTurnId: string;
      attachmentRef: string;
      documentVersionId: string;
      artifactRef: string;
      artifactSha256: string;
      locator: string;
    }
  | {
      kind: 'METHOD_CLAUSE';
      packRef: string;
      methodRef: string;
      sourceIdentity: string;
      locator: string;
      sourceVersionStatus: 'CONFIRMED' | 'VERSION_UNCONFIRMED';
    }
);

export interface AssessmentReadingResult {
  resultRef: string;
  resultRevision: number;
  scope:
    | { kind: 'WORK_ITEM'; workItemId: string; documentVersionId: string }
    | { kind: 'ENGINEERING_MATTER'; matterId: string };
  content: AssessmentReadingContent;
  evidence: AssessmentEvidence[];
  candidateOnly: true;
}

export interface AssessmentClaimEvidenceReadModel {
  resultRef: string;
  resultRevision: number;
  claim: AssessmentReadingClaim;
  evidence: AssessmentEvidence[];
}

/** A saved result projected for a directory row, without shortening its claims. */
export interface AssessmentReadingSummary {
  roundCompletion?: 'IN_PROGRESS' | 'COMPLETE' | 'COMPLETE_WITH_OPEN_QUESTIONS';
  resultRef: string;
  resultRevision: number;
  headline: string;
  listBrief: string;
  decisiveClaims: Array<{ claimId: string; text: string }>;
}
